### ISSUE TITLE
Bad contrast on inline code blocks-

### ISSUE THREAD

**Issue by lfritsch** [jd-solanki/slidev-dracula#1]
Using the most recent slidev version `0.40.3` and your theme in version `0.1.0`, inline code blocks are _very_ hard to read. 

Sadly, I'm unable to upload or attach pictures right now, github says "Something went really wrong, and we can't process that file".
But you should be able to replicate the issue.

**Comment by jd-solanki** [comment]
Can you please share screenshot?

**Comment by lfritsch** [comment]
https://imgur.com/a/LRqEvCm

**Comment by jd-solanki** [comment]
Thanks for sharing. Will release the new version with the fix 👍🏻

**Comment by RyanCavanaugh** [comment]
I could really use this - the theme is otherwise great, but I have a lot of inline code blocks and this is a blocker

**Comment by jd-solanki** [comment]
Hey @RyanCavanaugh 

I'll fix it this weekend, Stay tooned 👀 

Don't forget to watch for new releases, I'll maintain them ✅

**Comment by jd-solanki** [comment]
Hi @RyanCavanaugh @lfritsch I've made a new patch release, Can you please give it a try and let me know.

Awaiting response.

**Comment by RyanCavanaugh** [comment]
Looks great, thanks!
